// <auto-generated />
namespace BottleWormCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingStoreSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingStoreSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201804251453112_AddingStoreSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
